using System.Text.Json;
using SchoolERP.Application.Common.Exceptions;
using SchoolERP.Application.Common.Models;

namespace SchoolERP.Api.Middlewares;

/// <summary>
/// Global exception middleware.
/// 
/// WHY this exists:
/// - Avoids try/catch in every controller
/// - Converts internal exceptions into clean API responses
/// - Prevents sensitive error leaks
/// - Central place for logging & formatting errors
/// </summary>
public sealed class ExceptionHandlingMiddleware
{
    private readonly RequestDelegate _next;
    private readonly ILogger<ExceptionHandlingMiddleware> _logger;

    public ExceptionHandlingMiddleware(
        RequestDelegate next,
        ILogger<ExceptionHandlingMiddleware> logger)
    {
        _next = next;
        _logger = logger;
    }

    public async Task Invoke(HttpContext context)
    {
        try
        {
            // Let the request continue through the pipeline
            await _next(context);
        }
        catch (Exception ex)
        {
            // Every request has a trace identifier generated by ASP.NET
            // This is extremely useful in production to find logs
            var traceId = context.TraceIdentifier;

            // Log full exception details internally
            _logger.LogError(ex, "Unhandled exception | TraceId: {TraceId}", traceId);

            context.Response.ContentType = "application/json";

            ApiResponse<object> response;

            if (ex is AppException appEx)
            {
                // Business / expected exception
                context.Response.StatusCode = appEx.StatusCode;

                response = ApiResponse<object>.Fail(appEx.Message, traceId);
            }
            else
            {
                // Unexpected / system exception
                context.Response.StatusCode = 500;

                response = ApiResponse<object>.Fail(
                    "An unexpected error occurred. Please contact support.",
                    traceId);
            }

            await context.Response.WriteAsync(JsonSerializer.Serialize(response));
        }
    }
}
